sudo: false
language: ruby
rvm:
- 2.5.0
before_install: gem install bundler -v 1.17.1
deploy:
  provider: rubygems
  api_key:
    secure: VutHhspxyDKPtAq/09U3TRNoaDkOywmIdi1qpi9tG4q+hOGlNjs3+F2V1LMgFLmMFcEO+ihcUrEBj3tTieIfhk47QYFoU+8xIPGqNPCGuekDvwLSFg+2bR7EvnYtMLI92JHDdpdm/AJdCiHS8Z8bBXEK2rFEEVZvGUpvX/5SjwnVRx6EtJZJ0/EzPPUIJjhLrzjogJzdAcuUYvy6r1GXvlRHBvfjYNljsBlh1MKHSpQ/e3+vl2HE9q3BvJ1+yP+AFphzAtgqUjXepIY5FkyKYsqZWMv8PZlmUxNxZVfH9BRbLF6vQpdiCv+RXWHAgiqeP+umq9Fovj/xgChXLpyoJytSMWDZR1l05j+7PDvmS/CH4Pyjk6sMc3B609Tq1FQ8K0HbEGitieaESUjbReW++ihCcBNRpS7O64QIp56O0xW/spVsF4IO12sAE+oGslKFualGS1FaW2zdbJsjt7gdC3hlUTOrdaNSV1XzNVvl3ZqjbGVIrgpvuONqVfFeKBKhB7/yA3/PuWSC/Cj4AiTwFQbP2cFfZ5UwcLR+UWsdrrvjFx3Jdd/LAk4oV1D5khDTttZ03Id6Qwm9s1/ZNxe72Pl4bjeFhtGIYW7hMLbCUIy9PvWJBsCDgww7HEzWW1cI8WV5lmxcuZpRIW72uls8Pug4RwGmT/sbb0u98j0D9ek=
  gem: baremetrics_api
  on:
    tags: true
    repo: rewindio/baremetrics_api
